name: Staging

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest 
 
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_REMOTE_HOST }}
        USERNAME: ${{ secrets.SSH_REMOTE_USER }}
        PORT: 22 
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/var/www/html/fi-backend-v2"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        USERNAME: ${{ secrets.SSH_REMOTE_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          php artisan migrate
          sudo systemctl restart nginx
