name: Staging

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest 
 
    steps:
    - uses: actions/checkout@v1


    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        USERNAME: ${{ secrets.SSH_REMOTE_USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script:
          sudo systemctl restart myapp
