name: Staging

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.STG_REMOTE_HOST }}
        USERNAME: ${{ secrets.SSH_REMOTE_USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "."
        target: "/var/www/html/fi-backend"


    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STG_REMOTE_HOST }}
        USERNAME: ${{ secrets.SSH_REMOTE_USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.STG_PRIVATE_KEY }}
        script: |
          cd /var/www/html/fi-backend
          php artisan migrate
          php artisan cache:clear
          php artisan config:cache
